### ISSUE TITLE
Error when running main

### ISSUE THREAD

**Issue by Dan-carey** [j-mcnerney/growth-productionchains#1]
Hi,

I get an error when I try to run main (see below). I'm new to MATLAB but have followed the readme exactly, any advice is very welcome:

Error using save
Variable 'WIOD' not found.

Error in loadWIODbasicData (line 85)
save('./wrangle/wrangleWIOD/WIOD.mat', 'WIOD')

Error in wrangle_WIOD (line 3)
loadWIODbasicData

Error in main (line 25)
   wrangle_WIOD()

Thanks,
Dan

**Comment by j-mcnerney** [comment]
Hi Dan,

Thanks for letting me know.  Try this:

-Open wrangle > wrangleWIOD > loadWIODbasicData.m
-Change line 12 to
isDataFile    = contains({fileList.name}', 'WIOT'); % grab just the data
files


where the letters "WIOT" are capitalized.

I am guessing that in Matlab2017a, the contains function must not have been
case-sensitive.

Let me know if you have further issues.

Cheers,
James

**Comment by Dan-carey** [comment]
Hi James,

Thanks a ton for the speedy reply.

This has got past the first error but it now throws a separate one I don't understand when I type y after it asks to move WIOD, I've included the bit about not knowing mv above the error too, which technically starts after "Loading Data...":

Move saved WIOD mat file to ./save directory? (y/n)y
'mv' is not recognized as an internal or external command, 
operable program or batch file. 
Loading data...
Error using load
Unable to find file or directory './save/WIOD.mat'.

Error in loadWIOD (line 6)
load('./save/WIOD.mat')

Error in main (line 33)
   WorldEconomyBase = loadWIOD();               % WIOD
 

Thanks,
Dan

**Comment by j-mcnerney** [comment]
Hi Dan,

Thanks, sorry you are getting another error. Are you using Windows?
'mv' is the system command on mac and Linux to move a file, so that
could be why you are getting this.

As a workaround, try this:

-Move WIOD.mat by hand from "wrangle/wrangleWIOD/" to "save/".
-In main.m line 23, turn off the initial wrangling step by setting
"wrangle = false;" That will stop it from trying to build WIOD.mat
again.
-Run main.m

Best,
James

**Comment by Dan-carey** [comment]
Thanks James.

Sorry for the delay I was off work. This seemed to fix it, there were a couple of other minor things I managed to fix but also a major thing I wanted to mention for others who might try to run the code.

It seems when I put the data files into the data folder it orders them 00->11,95->99. Then when wrangling, the code enters things from loadWIODbasicdata into the WIOD struct in this order (including ValueAddedRows) but later things (like Labour and Cap compensation from AgumentHouseholdFlows) are entered into the WIOD struct in the order 95->99,00->11. This messes up the calculation of the exchange rates and therefore everything concerning prices later is off.

I managed to fix it by manually renaming the 95->99 WIOTs in the data folder to start with 1 through 5 respectively, so they are ordered 95->99,00->11. This causes me to get the same results as the paper. 

Thanks for the help,
Dan

**Comment by j-mcnerney** [comment]
Glad you were able to reproduce the results of the paper, and sorry you ran
into so many issues. Thanks for letting me know about the file ordering
issue so I can fix this for others. Happy to help with any other questions
about either the code or the results.

Cheers,
James
